name: Build and deploy CV
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare artifacts directory
      run: |
        mkdir -p ${{ github.workspace }}/artifacts
        mkdir -p ${{ github.workspace }}/artifacts/public
        
    - name: Build CV webpage
      run: | 
        chmod +x ${{ github.workspace }}/build-website/build.sh
        sudo ${{ github.workspace }}/build-website/build.sh
        cp -R ${{ github.workspace }}/build-website/public ${{ github.workspace }}/artifacts

    - name: npm install
      run: |
        cd ./build-pdf
        npm install

    - name: build PDF
      run: |
        cd ./build-pdf
        docker run -d --name cv-hugo-run -p 1313:1313 cv-hugo
        npm run build    
        cp  "Jerzy Wickowski - CV.pdf"  "${{ github.workspace }}/artifacts/public/Jerzy Wickowski - CV.pdf"

    - uses: actions/upload-artifact@v3
      with:
        name: Jerzy Wickowski CV
        path: ${{ github.workspace }}/artifacts           
      
    - name: Upload ftp
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: "artifacts/public/"
        server-dir: "/public_html/cv/"
        protocol: ftps
